server:
  port: 8080

spring:
  application:
    name: backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb-uri-placeholder}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:google-client-id-placeholder}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret-placeholder}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID:github-client-id-placeholder}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret-placeholder}
            scope:
              - read:user
              - user:email
